---
# file: roles/roborio/tasks/main.yml

- include: toolchain.yml
- include: wpilib.yml
- include: navx.yml
- include: ctre.yml

# this is ok because we only use this for admin user access
# admin user password is empty by default
- name: copy ssh private key to {{ vagrant_user }} user
  copy:
    src: roborio_2767
    dest: /home/{{ vagrant_user }}/.ssh/
    mode: 0600
    owner: "{{ vagrant_user }}"
    group: "{{ vagrant_user }}"
  tags: ssh

- name: copy ssh public key to {{ vagrant_user }} user
  copy:
    src: roborio_2767.pub
    dest: /home/{{ vagrant_user }}/.ssh/
    mode: 0644
    owner: "{{ vagrant_user }}"
    group: "{{ vagrant_user }}"
  tags: ssh

- name: configure {{ vagrant_user }} ssh for roboRIO
  blockinfile:
    dest: /home/{{ vagrant_user }}/.ssh/config
    create: yes
    state: present
    mode: 0600
    owner: "{{ vagrant_user }}"
    group: "{{ vagrant_user }}"
    block: |
      Host roborio
        IdentityFile ~/.ssh/roborio_2767
        HostName roborio-2767-frc.local
        User admin
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null
        LogLevel QUIET
