---
# file: roles/roborio/tasks/wpilib.yml


- include_vars: wpilib.yml
  tags: wpilib

- name: install unzip
  apt:
    name: unzip
    state: latest
    update_cache: no
  tags: wpilib


- name: download wpilib plugin
  get_url:
    url: "{{ wpilib_url }}"
    dest: /usr/local/src/{{ wpilib_jar }}
    checksum: sha256:{{ wpilib_sha256 }}
  register: wpilib_download
  tags: wpilib

- name: remove old WPILib
  file:
    path: /opt/wpilib/
    state: absent
  when: wpilib_download.changed

- name: extract to /opt/wpilib
  script: unarchive_wpilib.sh /usr/local/src/{{ wpilib_jar }} /opt/wpilib
  when: wpilib_download.changed
  tags: wpilib
