---
# file: site.yml

- include: common.yml
- include: atom.yml
- include: pyfrc.yml
- include: opencv.yml
- include: cmake.yml
- include: bazel.yml
- include: samba.yml
- include: nfs.yml
- include: deadeye.yml
# - include: virtualbox.yml
